{
 "title": "RED",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[1m]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/dialog/{toUuid}/get\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/dialog/{toUuid}/get\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/post/feed\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/post/feed\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/auth/user/email/{email}\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/auth/user/email/{email}\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/user/login\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/user/login\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/user/update\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/user/update\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/user/get/{uuid}\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/user/get/{uuid}\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/friend/set/{user_id}\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/friend/set/{user_id}\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/user/register\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/user/register\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v2/dialog/{toUuid}/get\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/api/v2/dialog/{toUuid}/get\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v2/dialog/{toUuid}/send\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/api/v2/dialog/{toUuid}/send\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v1/dialog/{toUuid}/get\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/api/v1/dialog/{toUuid}/get\"}[1m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v1/dialog/{toUuid}/send\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/api/v1/dialog/{toUuid}/send\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\"}[1m])) by (method, uri, instance)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\"}[1m]))"
    }
   ]
  }
 ]
}