global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["pgexp-pgmaster:9187", "pgexp-pgdialogs:9187", "pgexp-pgshard1:9187", "pgexp-pgshard2:9187"] #
  - job_name: hl-sonet-prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["sonet-post:8080", "sonet-core:8080", "sonet-dialog:8080"]